-ignorewarnings
-keep,includedescriptorclasses public class com.google.android.gms.common.GoogleApiAvailability { *; }
-keep,includedescriptorclasses public class com.google.android.gms.crash.internal.api.CrashApiImpl { *; }
-keep,includedescriptorclasses public class com.google.android.gms.tasks.OnCanceledListener { *; }
-keep,includedescriptorclasses public class com.google.android.gms.tasks.OnFailureListener { *; }
-keep,includedescriptorclasses public class com.google.android.gms.tasks.OnSuccessListener { *; }
-keep,includedescriptorclasses public class com.google.android.gms.tasks.Task { *; }
-keep,includedescriptorclasses public class com.google.firebase.example.LoggingUtils { * ; }
-keep,includedescriptorclasses public class com.google.firebase.analytics.FirebaseAnalytics { *; }
-keep,includedescriptorclasses public class com.google.firebase.example.LoggingUtils { * ; }